apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: abramb-smailand-stuff
spec:
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "97fd529d-b478-472f-ad46-6a2173b1a3d8"
            NODE_ENV: "production"
      secrets:
        - CLIENTSECRET
